-- init (up)
CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(50) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "uq_tags_name" ON "tags" ("name");

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "bio" TEXT,
  "password_hash" TEXT NOT NULL,
  "api_key" VARCHAR(64),
  "role" TEXT NOT NULL DEFAULT 'reader' CONSTRAINT "ck_users_role" CHECK ("role" IN ('admin', 'editor', 'reader')),
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "karma" INTEGER NOT NULL DEFAULT 0,
  "settings" JSONB,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "uq_users_api_key" ON "users" ("api_key");

CREATE UNIQUE INDEX "uq_users_email" ON "users" ("email");

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" BIGINT NOT NULL,
  "total" NUMERIC(19, 4) NOT NULL,
  "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
  "placed_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_orders_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

CREATE TABLE "posts" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "author_id" BIGINT NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "slug" VARCHAR(200),
  "body" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft' CONSTRAINT "ck_posts_status" CHECK ("status" IN ('draft', 'published', 'archived')),
  "views" BIGINT NOT NULL DEFAULT 0,
  "published_at" TIMESTAMPTZ,
  "cover" BYTEA,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_posts_author_id_status" ON "posts" ("author_id", "status");

CREATE UNIQUE INDEX "uq_posts_author_id_slug" ON "posts" ("author_id", "slug");

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "post_id" UUID NOT NULL,
  "user_id" BIGINT,
  "body" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_comments_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE TABLE "post_tags" (
  "post_id" UUID NOT NULL,
  "tag_id" INTEGER NOT NULL,
  PRIMARY KEY ("post_id", "tag_id"),
  CONSTRAINT "fk_post_tags_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_post_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE
);
