// Code generated by lathe. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/tobibamidele/lathe"
)

// Comment is a row of the "comments" table.
type Comment struct {
	ID        int64     `db:"id" json:"id"`
	PostID    uuid.UUID `db:"post_id" json:"post_id"`
	UserID    *int64    `db:"user_id" json:"user_id"`
	Body      string    `db:"body" json:"body"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`

	// Post is the Post this row belongs to. It is nil until loaded with With(db.Comments.Post) or Load.
	Post *Post `db:"-" json:"post,omitempty"`

	// User is the User this row belongs to. It is nil until loaded with With(db.Comments.User) or Load.
	User *User `db:"-" json:"user,omitempty"`
}

// CommentColumns holds a typed reference to every column of the "comments" table.
type CommentColumns struct {
	ID        lathe.Column[int64]
	PostID    lathe.Column[uuid.UUID]
	UserID    lathe.Column[int64]
	Body      lathe.Column[string]
	CreatedAt lathe.Column[time.Time]

	// Post is a relation to Post, for With, Load and LoadMany.
	Post lathe.Relation[Comment, Post]

	// User is a relation to User, for With, Load and LoadMany.
	User lathe.Relation[Comment, User]
}

// TableName returns "comments". It makes Comments usable in joins.
func (CommentColumns) TableName() string { return "comments" }

// Comments describes the "comments" table for use in queries:
//
//	client.Comments.FindMany().Where(Comments.ID.Eq(...))
var Comments = CommentColumns{
	ID:        lathe.NewColumn[int64]("comments", "id"),
	PostID:    lathe.NewColumn[uuid.UUID]("comments", "post_id"),
	UserID:    lathe.NewColumn[int64]("comments", "user_id"),
	Body:      lathe.NewColumn[string]("comments", "body"),
	CreatedAt: lathe.NewColumn[time.Time]("comments", "created_at"),
	Post: lathe.BelongsTo("Post", lathe.BelongsToSpec[Comment, Post]{
		Source: commentSpec, Target: postSpec,
		SourceCols: []string{"post_id"}, TargetCols: []string{"id"},
		Set: func(m *Comment, v *Post) { m.Post = v },
	}),
	User: lathe.BelongsTo("User", lathe.BelongsToSpec[Comment, User]{
		Source: commentSpec, Target: userSpec,
		SourceCols: []string{"user_id"}, TargetCols: []string{"id"},
		Set: func(m *Comment, v *User) { m.User = v },
	}),
}

var commentSpec = &lathe.TableSpec[Comment]{
	Table: "comments",
	Fields: []lathe.Field[Comment]{
		{Column: "id", Ptr: func(m *Comment) any { return &m.ID }, PrimaryKey: true, AutoIncrement: true},
		{Column: "post_id", Ptr: func(m *Comment) any { return &m.PostID }},
		{Column: "user_id", Ptr: func(m *Comment) any { return &m.UserID }},
		{Column: "body", Ptr: func(m *Comment) any { return &m.Body }},
		{Column: "created_at", Ptr: func(m *Comment) any { return &m.CreatedAt }, HasDefault: true},
	},
}

// CommentClient reads and writes the "comments" table. It embeds
// lathe.Model, which provides FindMany, FindFirst, Create, CreateMany, Save,
// Update, Delete, Count and Exists.
type CommentClient struct {
	*lathe.Model[Comment]
}

func newCommentClient(db *lathe.DB) *CommentClient {
	return &CommentClient{lathe.NewModel(db, commentSpec)}
}

// Get returns the row with the given primary key, or lathe.ErrNotFound.
func (c *CommentClient) Get(ctx context.Context, id int64) (*Comment, error) {
	return c.FindFirst().Where(Comments.ID.Eq(id)).One(ctx)
}
