// Code generated by lathe. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"github.com/tobibamidele/lathe"
)

// Order is a row of the "orders" table.
type Order struct {
	ID       int64           `db:"id" json:"id"`
	UserID   int64           `db:"user_id" json:"user_id"`
	Total    decimal.Decimal `db:"total" json:"total"`
	Currency string          `db:"currency" json:"currency"`
	PlacedAt time.Time       `db:"placed_at" json:"placed_at"`

	// User is the User this row belongs to. It is nil until loaded with With(db.Orders.User) or Load.
	User *User `db:"-" json:"user,omitempty"`
}

// OrderColumns holds a typed reference to every column of the "orders" table.
type OrderColumns struct {
	ID       lathe.Column[int64]
	UserID   lathe.Column[int64]
	Total    lathe.Column[decimal.Decimal]
	Currency lathe.Column[string]
	PlacedAt lathe.Column[time.Time]

	// User is a relation to User, for With, Load and LoadMany.
	User lathe.Relation[Order, User]
}

// TableName returns "orders". It makes Orders usable in joins.
func (OrderColumns) TableName() string { return "orders" }

// Orders describes the "orders" table for use in queries:
//
//	client.Orders.FindMany().Where(Orders.ID.Eq(...))
var Orders = OrderColumns{
	ID:       lathe.NewColumn[int64]("orders", "id"),
	UserID:   lathe.NewColumn[int64]("orders", "user_id"),
	Total:    lathe.NewColumn[decimal.Decimal]("orders", "total"),
	Currency: lathe.NewColumn[string]("orders", "currency"),
	PlacedAt: lathe.NewColumn[time.Time]("orders", "placed_at"),
	User: lathe.BelongsTo("User", lathe.BelongsToSpec[Order, User]{
		Source: orderSpec, Target: userSpec,
		SourceCols: []string{"user_id"}, TargetCols: []string{"id"},
		Set: func(m *Order, v *User) { m.User = v },
	}),
}

var orderSpec = &lathe.TableSpec[Order]{
	Table: "orders",
	Fields: []lathe.Field[Order]{
		{Column: "id", Ptr: func(m *Order) any { return &m.ID }, PrimaryKey: true, AutoIncrement: true},
		{Column: "user_id", Ptr: func(m *Order) any { return &m.UserID }},
		{Column: "total", Ptr: func(m *Order) any { return &m.Total }},
		{Column: "currency", Ptr: func(m *Order) any { return &m.Currency }, HasDefault: true},
		{Column: "placed_at", Ptr: func(m *Order) any { return &m.PlacedAt }, HasDefault: true},
	},
}

// OrderClient reads and writes the "orders" table. It embeds
// lathe.Model, which provides FindMany, FindFirst, Create, CreateMany, Save,
// Update, Delete, Count and Exists.
type OrderClient struct {
	*lathe.Model[Order]
}

func newOrderClient(db *lathe.DB) *OrderClient {
	return &OrderClient{lathe.NewModel(db, orderSpec)}
}

// Get returns the row with the given primary key, or lathe.ErrNotFound.
func (c *OrderClient) Get(ctx context.Context, id int64) (*Order, error) {
	return c.FindFirst().Where(Orders.ID.Eq(id)).One(ctx)
}
