// Code generated by lathe. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/tobibamidele/lathe"
)

// Post is a row of the "posts" table.
type Post struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	AuthorID    int64      `db:"author_id" json:"author_id"`
	Title       string     `db:"title" json:"title"`
	Slug        *string    `db:"slug" json:"slug"`
	Body        *string    `db:"body" json:"body"`
	Status      PostStatus `db:"status" json:"status"`
	Views       int64      `db:"views" json:"views"`
	PublishedAt *time.Time `db:"published_at" json:"published_at"`
	Cover       []byte     `db:"cover" json:"cover"`
}

// PostStatus is the set of values of Post.Status.
type PostStatus string

// Values of PostStatus.
const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

// PostStatusValues lists every valid PostStatus.
func PostStatusValues() []PostStatus {
	return []PostStatus{PostStatusDraft, PostStatusPublished, PostStatusArchived}
}

// Valid reports whether v is one of the declared values.
func (v PostStatus) Valid() bool {
	switch v {
	case PostStatusDraft, PostStatusPublished, PostStatusArchived:
		return true
	}
	return false
}

// PostColumns holds a typed reference to every column of the "posts" table.
type PostColumns struct {
	ID          lathe.Column[uuid.UUID]
	AuthorID    lathe.Column[int64]
	Title       lathe.Column[string]
	Slug        lathe.Column[string]
	Body        lathe.Column[string]
	Status      lathe.Column[PostStatus]
	Views       lathe.Column[int64]
	PublishedAt lathe.Column[time.Time]
	Cover       lathe.Column[[]byte]
}

// TableName returns "posts". It makes Posts usable in joins.
func (PostColumns) TableName() string { return "posts" }

// Posts describes the "posts" table for use in queries:
//
//	client.Posts.FindMany().Where(Posts.ID.Eq(...))
var Posts = PostColumns{
	ID:          lathe.NewColumn[uuid.UUID]("posts", "id"),
	AuthorID:    lathe.NewColumn[int64]("posts", "author_id"),
	Title:       lathe.NewColumn[string]("posts", "title"),
	Slug:        lathe.NewColumn[string]("posts", "slug"),
	Body:        lathe.NewColumn[string]("posts", "body"),
	Status:      lathe.NewColumn[PostStatus]("posts", "status"),
	Views:       lathe.NewColumn[int64]("posts", "views"),
	PublishedAt: lathe.NewColumn[time.Time]("posts", "published_at"),
	Cover:       lathe.NewColumn[[]byte]("posts", "cover"),
}

var postSpec = &lathe.TableSpec[Post]{
	Table: "posts",
	Fields: []lathe.Field[Post]{
		{Column: "id", Ptr: func(m *Post) any { return &m.ID }, PrimaryKey: true, HasDefault: true, Default: func(m *Post) {
			if m.ID == uuid.Nil {
				m.ID = uuid.New()
			}
		}},
		{Column: "author_id", Ptr: func(m *Post) any { return &m.AuthorID }},
		{Column: "title", Ptr: func(m *Post) any { return &m.Title }},
		{Column: "slug", Ptr: func(m *Post) any { return &m.Slug }},
		{Column: "body", Ptr: func(m *Post) any { return &m.Body }},
		{Column: "status", Ptr: func(m *Post) any { return &m.Status }, HasDefault: true},
		{Column: "views", Ptr: func(m *Post) any { return &m.Views }},
		{Column: "published_at", Ptr: func(m *Post) any { return &m.PublishedAt }},
		{Column: "cover", Ptr: func(m *Post) any { return &m.Cover }},
	},
}

// PostClient reads and writes the "posts" table. It embeds
// lathe.Model, which provides FindMany, FindFirst, Create, CreateMany, Save,
// Update, Delete, Count and Exists.
type PostClient struct {
	*lathe.Model[Post]
}

func newPostClient(db *lathe.DB) *PostClient {
	return &PostClient{lathe.NewModel(db, postSpec)}
}

// Get returns the row with the given primary key, or lathe.ErrNotFound.
func (c *PostClient) Get(ctx context.Context, id uuid.UUID) (*Post, error) {
	return c.FindFirst().Where(Posts.ID.Eq(id)).One(ctx)
}
