// Code generated by lathe. DO NOT EDIT.

package db

import (
	"context"

	"github.com/tobibamidele/lathe"
)

// Tag is a row of the "tags" table.
type Tag struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

// TagColumns holds a typed reference to every column of the "tags" table.
type TagColumns struct {
	ID   lathe.Column[int32]
	Name lathe.Column[string]
}

// TableName returns "tags". It makes Tags usable in joins.
func (TagColumns) TableName() string { return "tags" }

// Tags describes the "tags" table for use in queries:
//
//	client.Tags.FindMany().Where(Tags.ID.Eq(...))
var Tags = TagColumns{
	ID:   lathe.NewColumn[int32]("tags", "id"),
	Name: lathe.NewColumn[string]("tags", "name"),
}

var tagSpec = &lathe.TableSpec[Tag]{
	Table: "tags",
	Fields: []lathe.Field[Tag]{
		{Column: "id", Ptr: func(m *Tag) any { return &m.ID }, PrimaryKey: true, AutoIncrement: true},
		{Column: "name", Ptr: func(m *Tag) any { return &m.Name }},
	},
}

// TagClient reads and writes the "tags" table. It embeds
// lathe.Model, which provides FindMany, FindFirst, Create, CreateMany, Save,
// Update, Delete, Count and Exists.
type TagClient struct {
	*lathe.Model[Tag]
}

func newTagClient(db *lathe.DB) *TagClient {
	return &TagClient{lathe.NewModel(db, tagSpec)}
}

// Get returns the row with the given primary key, or lathe.ErrNotFound.
func (c *TagClient) Get(ctx context.Context, id int32) (*Tag, error) {
	return c.FindFirst().Where(Tags.ID.Eq(id)).One(ctx)
}
