// Code generated by lathe. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"github.com/tobibamidele/lathe"
)

// User is a row of the "users" table.
type User struct {
	ID           int64      `db:"id" json:"id"`
	Email        string     `db:"email" json:"email"`
	Name         string     `db:"name" json:"name"`
	Bio          *string    `db:"bio" json:"bio"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	APIKey       *string    `db:"api_key" json:"api_key"`
	Role         UserRole   `db:"role" json:"role"`
	Active       bool       `db:"active" json:"active"`
	Karma        int32      `db:"karma" json:"karma"`
	Settings     lathe.JSON `db:"settings" json:"settings"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
}

// UserRole is the set of values of User.Role.
type UserRole string

// Values of UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
	UserRoleReader UserRole = "reader"
)

// UserRoleValues lists every valid UserRole.
func UserRoleValues() []UserRole {
	return []UserRole{UserRoleAdmin, UserRoleEditor, UserRoleReader}
}

// Valid reports whether v is one of the declared values.
func (v UserRole) Valid() bool {
	switch v {
	case UserRoleAdmin, UserRoleEditor, UserRoleReader:
		return true
	}
	return false
}

// UserColumns holds a typed reference to every column of the "users" table.
type UserColumns struct {
	ID           lathe.Column[int64]
	Email        lathe.Column[string]
	Name         lathe.Column[string]
	Bio          lathe.Column[string]
	PasswordHash lathe.Column[string]
	APIKey       lathe.Column[string]
	Role         lathe.Column[UserRole]
	Active       lathe.Column[bool]
	Karma        lathe.Column[int32]
	Settings     lathe.Column[lathe.JSON]
	CreatedAt    lathe.Column[time.Time]
}

// TableName returns "users". It makes Users usable in joins.
func (UserColumns) TableName() string { return "users" }

// Users describes the "users" table for use in queries:
//
//	client.Users.FindMany().Where(Users.ID.Eq(...))
var Users = UserColumns{
	ID:           lathe.NewColumn[int64]("users", "id"),
	Email:        lathe.NewColumn[string]("users", "email"),
	Name:         lathe.NewColumn[string]("users", "name"),
	Bio:          lathe.NewColumn[string]("users", "bio"),
	PasswordHash: lathe.NewColumn[string]("users", "password_hash"),
	APIKey:       lathe.NewColumn[string]("users", "api_key"),
	Role:         lathe.NewColumn[UserRole]("users", "role"),
	Active:       lathe.NewColumn[bool]("users", "active"),
	Karma:        lathe.NewColumn[int32]("users", "karma"),
	Settings:     lathe.NewColumn[lathe.JSON]("users", "settings"),
	CreatedAt:    lathe.NewColumn[time.Time]("users", "created_at"),
}

var userSpec = &lathe.TableSpec[User]{
	Table: "users",
	Fields: []lathe.Field[User]{
		{Column: "id", Ptr: func(m *User) any { return &m.ID }, PrimaryKey: true, AutoIncrement: true},
		{Column: "email", Ptr: func(m *User) any { return &m.Email }},
		{Column: "name", Ptr: func(m *User) any { return &m.Name }},
		{Column: "bio", Ptr: func(m *User) any { return &m.Bio }},
		{Column: "password_hash", Ptr: func(m *User) any { return &m.PasswordHash }},
		{Column: "api_key", Ptr: func(m *User) any { return &m.APIKey }},
		{Column: "role", Ptr: func(m *User) any { return &m.Role }, HasDefault: true},
		{Column: "active", Ptr: func(m *User) any { return &m.Active }},
		{Column: "karma", Ptr: func(m *User) any { return &m.Karma }},
		{Column: "settings", Ptr: func(m *User) any { return &m.Settings }},
		{Column: "created_at", Ptr: func(m *User) any { return &m.CreatedAt }, HasDefault: true},
	},
}

// UserClient reads and writes the "users" table. It embeds
// lathe.Model, which provides FindMany, FindFirst, Create, CreateMany, Save,
// Update, Delete, Count and Exists.
type UserClient struct {
	*lathe.Model[User]
}

func newUserClient(db *lathe.DB) *UserClient {
	return &UserClient{lathe.NewModel(db, userSpec)}
}

// Get returns the row with the given primary key, or lathe.ErrNotFound.
func (c *UserClient) Get(ctx context.Context, id int64) (*User, error) {
	return c.FindFirst().Where(Users.ID.Eq(id)).One(ctx)
}
