// Package schema is the declarative half of lathe.
//
// A project describes its database in ordinary Go code using the builders in
// this package. The lathe CLI loads that description, turns it into a
// [Snapshot] (a plain, JSON-serialisable value), and uses the snapshot to
// generate Go code and SQL migrations.
//
// Every column constructor returns a *ColumnBuilder parameterised by the
// column's Go type. Use [ColumnBuilder.DefaultFunc] to supply the column's
// value per insert from an exported function in this package, with the type
// checked against the column.
package schema

import (
	"reflect"
	"sort"
)

// Dialect identifies a supported database engine.
type Dialect string

// Supported dialects.
const (
	Postgres Dialect = "postgres"
	MySQL    Dialect = "mysql"
	SQLite   Dialect = "sqlite"
)

// Valid reports whether d is a supported dialect.
func (d Dialect) Valid() bool {
	switch d {
	case Postgres, MySQL, SQLite:
		return true
	}
	return false
}

// Kind is the logical (database independent) type of a column.
type Kind string

// Column kinds.
const (
	KindSmallInt  Kind = "smallint"
	KindInt       Kind = "int"
	KindBigInt    Kind = "bigint"
	KindReal      Kind = "real"
	KindDouble    Kind = "double"
	KindDecimal   Kind = "decimal"
	KindBool      Kind = "bool"
	KindVarChar   Kind = "varchar"
	KindText      Kind = "text"
	KindUUID      Kind = "uuid"
	KindTimestamp Kind = "timestamp"
	KindDate      Kind = "date"
	KindJSON      Kind = "json"
	KindBytes     Kind = "bytes"
	KindEnum      Kind = "enum"
)

// IsInteger reports whether k is an integer kind.
func (k Kind) IsInteger() bool {
	return k == KindSmallInt || k == KindInt || k == KindBigInt
}

// IsNumeric reports whether k stores numbers.
func (k Kind) IsNumeric() bool {
	return k.IsInteger() || k == KindReal || k == KindDouble || k == KindDecimal
}

// IsString reports whether k is stored as text and accepts string literals.
func (k Kind) IsString() bool {
	switch k {
	case KindVarChar, KindText, KindUUID, KindEnum, KindTimestamp, KindDate:
		return true
	}
	return false
}

// Type is a column type together with its parameters.
type Type struct {
	Kind      Kind     `json:"kind"`
	Length    int      `json:"length,omitempty"`    // varchar
	Precision int      `json:"precision,omitempty"` // decimal
	Scale     int      `json:"scale,omitempty"`     // decimal
	Values    []string `json:"values,omitempty"`    // enum
}

// Equal reports whether two types are identical.
func (t Type) Equal(o Type) bool {
	return t.Kind == o.Kind && t.Length == o.Length && t.Precision == o.Precision &&
		t.Scale == o.Scale && reflect.DeepEqual(t.Values, o.Values)
}

// Action is a referential action for foreign keys.
type Action string

// Referential actions. The zero value means the database default (NO ACTION).
const (
	NoAction   Action = ""
	Cascade    Action = "CASCADE"
	Restrict   Action = "RESTRICT"
	SetNull    Action = "SET NULL"
	SetDefault Action = "SET DEFAULT"
)

// DefaultKind describes how a column default is produced.
type DefaultKind string

// Default kinds.
const (
	DefaultLiteral DefaultKind = "literal" // a constant
	DefaultNow     DefaultKind = "now"     // current timestamp
	DefaultUUID    DefaultKind = "uuid"    // random UUID generated by the database
	DefaultExpr    DefaultKind = "expr"    // verbatim SQL expression
)

// LiteralKind is the lexical class of a literal default.
type LiteralKind string

// Literal kinds.
const (
	LitString LiteralKind = "string"
	LitNumber LiteralKind = "number"
	LitBool   LiteralKind = "bool"
)

// Default is a server-side column default.
type Default struct {
	Kind  DefaultKind `json:"kind"`
	Lit   LiteralKind `json:"lit,omitempty"`
	Value string      `json:"value,omitempty"`
}

// Column describes a single table column.
type ColumnDef struct {
	Name          string   `json:"name"`
	Type          Type     `json:"type"`
	Nullable      bool     `json:"nullable,omitempty"`
	Default       *Default `json:"default,omitempty"`
	AutoIncrement bool     `json:"autoIncrement,omitempty"`

	// DefaultFunc names a package-level function in the schema package that
	// supplies the column's value per insert, in Go. It is a code generation
	// hint only: the column has no server-side default. Written as the fully
	// qualified name, e.g. "example.com/internal/schema.GenerateID".
	DefaultFunc string `json:"defaultFunc,omitempty"`

	// Field overrides the generated Go field name.
	Field string `json:"field,omitempty"`
	// RenamedFrom is a migration hint: the previous column name.
	RenamedFrom string `json:"renamedFrom,omitempty"`
}

// SameDDL reports whether two columns produce identical DDL (ignoring names
// and code generation hints).
func (c *ColumnDef) SameDDL(o *ColumnDef) bool {
	return c.Type.Equal(o.Type) && c.Nullable == o.Nullable &&
		c.AutoIncrement == o.AutoIncrement && reflect.DeepEqual(c.Default, o.Default)
}

// Index describes a (possibly unique) index.
type IndexDef struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
	Unique  bool     `json:"unique,omitempty"`
}

// Equal reports whether two indexes are identical.
func (i *IndexDef) Equal(o *IndexDef) bool {
	return i.Name == o.Name && i.Unique == o.Unique && reflect.DeepEqual(i.Columns, o.Columns)
}

// ForeignKey describes a foreign key constraint.
type ForeignKeyDef struct {
	Name       string   `json:"name"`
	Columns    []string `json:"columns"`
	RefTable   string   `json:"refTable"`
	RefColumns []string `json:"refColumns"`
	OnDelete   Action   `json:"onDelete,omitempty"`
	OnUpdate   Action   `json:"onUpdate,omitempty"`

	// Relation and Reverse name the generated relation fields: Relation on the
	// table that holds the foreign key (belongs-to), Reverse on the referenced
	// table (has-many or has-one). Empty means "derive a name"; "-" means "do
	// not generate". Code generation hints only.
	Relation string `json:"relation,omitempty"`
	Reverse  string `json:"reverse,omitempty"`
}

// Equal reports whether two foreign keys produce identical DDL (relation names
// are ignored).
func (f *ForeignKeyDef) Equal(o *ForeignKeyDef) bool {
	return f.Name == o.Name && f.RefTable == o.RefTable && f.OnDelete == o.OnDelete &&
		f.OnUpdate == o.OnUpdate && reflect.DeepEqual(f.Columns, o.Columns) &&
		reflect.DeepEqual(f.RefColumns, o.RefColumns)
}

// Table describes a database table.
type TableDef struct {
	Name        string           `json:"name"`
	Columns     []*ColumnDef     `json:"columns"`
	PrimaryKey  []string         `json:"primaryKey"`
	Indexes     []*IndexDef      `json:"indexes,omitempty"`
	ForeignKeys []*ForeignKeyDef `json:"foreignKeys,omitempty"`

	// Model overrides the generated Go struct name.
	Model string `json:"model,omitempty"`
	// RenamedFrom is a migration hint: the previous table name.
	RenamedFrom string `json:"renamedFrom,omitempty"`
}

// Column returns the named column or nil.
func (t *TableDef) Column(name string) *ColumnDef {
	for _, c := range t.Columns {
		if c.Name == name {
			return c
		}
	}
	return nil
}

// Index returns the named index or nil.
func (t *TableDef) Index(name string) *IndexDef {
	for _, i := range t.Indexes {
		if i.Name == name {
			return i
		}
	}
	return nil
}

// ForeignKey returns the named foreign key or nil.
func (t *TableDef) ForeignKey(name string) *ForeignKeyDef {
	for _, f := range t.ForeignKeys {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// IsPrimaryKey reports whether the named column is part of the primary key.
func (t *TableDef) IsPrimaryKey(col string) bool {
	for _, c := range t.PrimaryKey {
		if c == col {
			return true
		}
	}
	return false
}

// Clone returns a deep copy of the table.
func (t *TableDef) Clone() *TableDef {
	n := *t
	n.Columns = make([]*ColumnDef, len(t.Columns))
	for i, c := range t.Columns {
		cc := *c
		if c.Default != nil {
			d := *c.Default
			cc.Default = &d
		}
		cc.Type.Values = append([]string(nil), c.Type.Values...)
		n.Columns[i] = &cc
	}
	n.PrimaryKey = append([]string(nil), t.PrimaryKey...)
	n.Indexes = make([]*IndexDef, len(t.Indexes))
	for i, ix := range t.Indexes {
		c := *ix
		c.Columns = append([]string(nil), ix.Columns...)
		n.Indexes[i] = &c
	}
	n.ForeignKeys = make([]*ForeignKeyDef, len(t.ForeignKeys))
	for i, fk := range t.ForeignKeys {
		c := *fk
		c.Columns = append([]string(nil), fk.Columns...)
		c.RefColumns = append([]string(nil), fk.RefColumns...)
		n.ForeignKeys[i] = &c
	}
	return &n
}

// SnapshotVersion is the current snapshot format version.
const SnapshotVersion = 1

// Snapshot is the complete, normalised state of a schema at a point in time.
// It is what lathe persists next to migrations and what it diffs against.
type Snapshot struct {
	Version int         `json:"version"`
	Dialect Dialect     `json:"dialect"`
	Tables  []*TableDef `json:"tables"`
}

// Table returns the named table or nil.
func (s *Snapshot) Table(name string) *TableDef {
	for _, t := range s.Tables {
		if t.Name == name {
			return t
		}
	}
	return nil
}

// StripHints returns a copy of the snapshot without migration hints, which
// only apply to the diff they were written for.
func (s *Snapshot) StripHints() *Snapshot {
	n := &Snapshot{Version: s.Version, Dialect: s.Dialect}
	for _, t := range s.Tables {
		c := t.Clone()
		c.RenamedFrom = ""
		for _, col := range c.Columns {
			col.RenamedFrom = ""
		}
		n.Tables = append(n.Tables, c)
	}
	return n
}

func (s *Snapshot) sort() {
	sort.Slice(s.Tables, func(i, j int) bool { return s.Tables[i].Name < s.Tables[j].Name })
	for _, t := range s.Tables {
		sort.Slice(t.Indexes, func(i, j int) bool { return t.Indexes[i].Name < t.Indexes[j].Name })
		sort.Slice(t.ForeignKeys, func(i, j int) bool { return t.ForeignKeys[i].Name < t.ForeignKeys[j].Name })
	}
}
