package plan_test

import (
	"strings"
	"testing"

	"github.com/tobibamidele/lathe/internal/ddl"
	"github.com/tobibamidele/lathe/internal/plan"
	s "github.com/tobibamidele/lathe/schema"
)

func snap(t *testing.T, d s.Dialect, tables ...*s.TableBuilder) *s.Snapshot {
	t.Helper()
	exp, err := s.New(s.Config{Dialect: d}, tables...).Export()
	if err != nil {
		t.Fatal(err)
	}
	return exp.Snapshot
}

func diff(t *testing.T, old, cur *s.Snapshot) (*plan.Plan, ddl.Dialect) {
	t.Helper()
	d, err := ddl.For(cur.Dialect)
	if err != nil {
		t.Fatal(err)
	}
	p, err := plan.Diff(old, cur, d)
	if err != nil {
		t.Fatal(err)
	}
	return p, d
}

func up(t *testing.T, p *plan.Plan, d ddl.Dialect) string {
	t.Helper()
	stmts, err := p.Up(d)
	if err != nil {
		t.Fatal(err)
	}
	return strings.Join(stmts, ";\n")
}

func down(t *testing.T, p *plan.Plan, d ddl.Dialect) string {
	t.Helper()
	stmts, err := p.Down(d)
	if err != nil {
		t.Fatal(err)
	}
	return strings.Join(stmts, ";\n")
}

func mustContain(t *testing.T, got string, want ...string) {
	t.Helper()
	for _, w := range want {
		if !strings.Contains(got, w) {
			t.Errorf("missing %q in:\n%s", w, got)
		}
	}
}

func mustNotContain(t *testing.T, got string, bad ...string) {
	t.Helper()
	for _, w := range bad {
		if strings.Contains(got, w) {
			t.Errorf("unexpected %q in:\n%s", w, got)
		}
	}
}

func users() *s.TableBuilder {
	return s.Table("users",
		s.BigInt("id").PrimaryKey().AutoIncrement(),
		s.VarChar("email", 255).Unique(),
		s.Enum("role", "admin", "member").Default("member"),
		s.Money("balance").Default("0"),
		s.Timestamp("created_at").DefaultNow(),
	)
}

func posts() *s.TableBuilder {
	return s.Table("posts",
		s.UUID("id").PrimaryKey().DefaultUUID(),
		s.BigInt("author_id").References("users", "id").OnDelete(s.Cascade).Index(),
		s.Text("body").Nullable(),
	)
}

func TestCreateEachDialect(t *testing.T) {
	cases := map[s.Dialect][]string{
		s.Postgres: {
			`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
			`"role" TEXT NOT NULL DEFAULT 'member' CONSTRAINT "ck_users_role" CHECK ("role" IN ('admin', 'member'))`,
			`"balance" NUMERIC(19, 4) NOT NULL DEFAULT 0`,
			`"created_at" TIMESTAMPTZ NOT NULL DEFAULT now()`,
			`"id" UUID NOT NULL DEFAULT gen_random_uuid()`,
			`CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE`,
			`CREATE UNIQUE INDEX "uq_users_email" ON "users" ("email")`,
		},
		s.MySQL: {
			"`id` BIGINT NOT NULL AUTO_INCREMENT",
			"`role` ENUM('admin', 'member') NOT NULL DEFAULT 'member'",
			"`created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)",
			"`id` CHAR(36) NOT NULL DEFAULT (UUID())",
			"`body` TEXT NULL",
			"CREATE INDEX `idx_posts_author_id` ON `posts` (`author_id`)",
		},
		s.SQLite: {
			`"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL`,
			`"balance" DECIMAL(19, 4) NOT NULL DEFAULT 0`,
			`"created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP`,
			`CONSTRAINT "ck_users_role" CHECK ("role" IN ('admin', 'member'))`,
			`"body" TEXT`,
		},
	}
	for dialect, wants := range cases {
		t.Run(string(dialect), func(t *testing.T) {
			p, d := diff(t, nil, snap(t, dialect, users(), posts()))
			got := up(t, p, d)
			mustContain(t, got, wants...)
			// users must be created before posts everywhere (FK target first)
			if strings.Index(got, "CREATE TABLE "+d.Quote("users")) > strings.Index(got, "CREATE TABLE "+d.Quote("posts")) {
				t.Errorf("users must be created before posts:\n%s", got)
			}
			dn := down(t, p, d)
			if strings.Index(dn, "DROP TABLE "+d.Quote("posts")) > strings.Index(dn, "DROP TABLE "+d.Quote("users")) {
				t.Errorf("posts must be dropped before users:\n%s", dn)
			}
		})
	}
}

func TestNoChanges(t *testing.T) {
	a := snap(t, s.Postgres, users(), posts())
	b := snap(t, s.Postgres, users(), posts())
	if p, _ := diff(t, a, b); !p.Empty() {
		t.Errorf("identical snapshots should not produce a plan: %v", p.Describe())
	}
}

func TestDialectChangeRejected(t *testing.T) {
	d, _ := ddl.For(s.MySQL)
	_, err := plan.Diff(snap(t, s.Postgres, users()), snap(t, s.MySQL, users()), d)
	if err == nil || !strings.Contains(err.Error(), "dialect changed") {
		t.Fatalf("want dialect error, got %v", err)
	}
}

func TestCircularForeignKeys(t *testing.T) {
	a := s.Table("a", s.Int("id").PrimaryKey(), s.Int("b_id").Nullable().References("b", "id"))
	b := s.Table("b", s.Int("id").PrimaryKey(), s.Int("a_id").Nullable().References("a", "id"))
	for _, dialect := range []s.Dialect{s.Postgres, s.MySQL} {
		t.Run(string(dialect), func(t *testing.T) {
			p, d := diff(t, nil, snap(t, dialect, a, b))
			got := up(t, p, d)
			// exactly one FK is deferred to an ALTER TABLE, after both tables exist
			if n := strings.Count(got, "ADD CONSTRAINT"); n != 1 {
				t.Errorf("want 1 deferred foreign key, got %d:\n%s", n, got)
			}
			if strings.Index(got, "ADD CONSTRAINT") < strings.LastIndex(got, "CREATE TABLE") {
				t.Errorf("deferred FK must come after all CREATE TABLEs:\n%s", got)
			}
			dn := down(t, p, d)
			if !strings.HasPrefix(dn, "ALTER TABLE") {
				t.Errorf("down must drop the deferred FK first:\n%s", dn)
			}
		})
	}
	// SQLite resolves references lazily, so everything stays inline.
	p, d := diff(t, nil, snap(t, s.SQLite, a, b))
	mustNotContain(t, up(t, p, d), "ADD CONSTRAINT")
}

func TestAddAndDropColumn(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("t", s.Int("id").PrimaryKey(), s.Text("gone")))
	cur := snap(t, s.Postgres, s.Table("t", s.Int("id").PrimaryKey(), s.Text("bio").Nullable()))
	p, d := diff(t, old, cur)
	mustContain(t, up(t, p, d), `ALTER TABLE "t" DROP COLUMN "gone"`, `ALTER TABLE "t" ADD COLUMN "bio" TEXT`)
	mustContain(t, down(t, p, d), `ALTER TABLE "t" DROP COLUMN "bio"`, `ALTER TABLE "t" ADD COLUMN "gone" TEXT NOT NULL`)
	if w := p.Warnings(); len(w) != 1 || !strings.Contains(w[0], "drops column t.gone") {
		t.Errorf("want data loss warning, got %v", w)
	}
}

func TestAlterColumnPostgres(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("t",
		s.Int("id").PrimaryKey(),
		s.VarChar("name", 50).Default("x"),
		s.Text("note").Nullable(),
		s.Enum("kind", "a", "b"),
	))
	cur := snap(t, s.Postgres, s.Table("t",
		s.Int("id").PrimaryKey(),
		s.VarChar("name", 100).Default("y"),
		s.Text("note"),
		s.Enum("kind", "a", "b", "c"),
	))
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	mustContain(t, got,
		`ALTER COLUMN "name" DROP DEFAULT`,
		`ALTER COLUMN "name" TYPE VARCHAR(100) USING "name"::VARCHAR(100)`,
		`ALTER COLUMN "name" SET DEFAULT 'y'`,
		`ALTER COLUMN "note" SET NOT NULL`,
		`DROP CONSTRAINT "ck_t_kind"`,
		`ADD CONSTRAINT "ck_t_kind" CHECK ("kind" IN ('a', 'b', 'c'))`,
	)
	if len(p.Warnings()) == 0 {
		t.Error("type change should warn")
	}
	mustContain(t, down(t, p, d), `ALTER COLUMN "note" DROP NOT NULL`, `TYPE VARCHAR(50)`)
}

func TestAlterColumnMySQL(t *testing.T) {
	old := snap(t, s.MySQL, s.Table("t", s.Int("id").PrimaryKey(), s.VarChar("name", 50)))
	cur := snap(t, s.MySQL, s.Table("t", s.Int("id").PrimaryKey(), s.VarChar("name", 100).Nullable()))
	p, d := diff(t, old, cur)
	mustContain(t, up(t, p, d), "ALTER TABLE `t` MODIFY COLUMN `name` VARCHAR(100) NULL")
}

func TestRenames(t *testing.T) {
	old := snap(t, s.Postgres,
		s.Table("accounts", s.Int("id").PrimaryKey(), s.Text("name")),
		s.Table("notes", s.Int("id").PrimaryKey(), s.Int("account_id").References("accounts", "id")),
	)
	cur := snap(t, s.Postgres,
		s.Table("users", s.Int("id").PrimaryKey(), s.Text("full_name").RenamedFrom("name")).RenamedFrom("accounts"),
		s.Table("notes", s.Int("id").PrimaryKey(), s.Int("account_id").References("users", "id")),
	)
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	mustContain(t, got, `ALTER TABLE "accounts" RENAME TO "users"`, `ALTER TABLE "users" RENAME COLUMN "name" TO "full_name"`)
	mustNotContain(t, got, "DROP TABLE", "DROP COLUMN", "CREATE TABLE")
	// the FK in notes only changed because its target was renamed: no churn
	mustNotContain(t, got, "FOREIGN KEY", "DROP CONSTRAINT")
	dn := down(t, p, d)
	mustContain(t, dn, `RENAME COLUMN "full_name" TO "name"`, `ALTER TABLE "users" RENAME TO "accounts"`)
}

func TestStaleRenameHintIsIgnored(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("people", s.Int("id").PrimaryKey(), s.Text("full_name")))
	cur := snap(t, s.Postgres, s.Table("people", s.Int("id").PrimaryKey(), s.Text("full_name").RenamedFrom("name")).RenamedFrom("users"))
	if p, _ := diff(t, old, cur); !p.Empty() {
		t.Errorf("a hint for an already applied rename must be a no-op: %v", p.Describe())
	}
}

func TestRenameHintConflict(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("a", s.Int("id").PrimaryKey()))
	cur := snap(t, s.Postgres, s.Table("a", s.Int("id").PrimaryKey()), s.Table("b", s.Int("id").PrimaryKey()).RenamedFrom("a"))
	d, _ := ddl.For(s.Postgres)
	if _, err := plan.Diff(old, cur, d); err == nil || !strings.Contains(err.Error(), "still exists") {
		t.Fatalf("want conflict error, got %v", err)
	}
}

func TestPrimaryKeyChangeIsRefused(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("t", s.Int("id").PrimaryKey(), s.Int("b")))
	cur := snap(t, s.Postgres, s.Table("t", s.Int("id"), s.Int("b").PrimaryKey()))
	d, _ := ddl.For(s.Postgres)
	_, err := plan.Diff(old, cur, d)
	if err == nil || !strings.Contains(err.Error(), "primary key changed") {
		t.Fatalf("want primary key error, got %v", err)
	}
}

func TestIndexAndForeignKeyChanges(t *testing.T) {
	old := snap(t, s.Postgres,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("t", s.Int("id").PrimaryKey(), s.Int("u_id").References("u", "id"), s.Text("a"), s.Index("a")),
	)
	cur := snap(t, s.Postgres,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("t", s.Int("id").PrimaryKey(), s.Int("u_id").References("u", "id").OnDelete(s.Cascade), s.Text("a"), s.UniqueIndex("a")),
	)
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	mustContain(t, got, `DROP INDEX "idx_t_a"`, `CREATE UNIQUE INDEX "uq_t_a"`,
		`DROP CONSTRAINT "fk_t_u_id"`, `ADD CONSTRAINT "fk_t_u_id" FOREIGN KEY ("u_id") REFERENCES "u" ("id") ON DELETE CASCADE`)
	if strings.Index(got, "DROP CONSTRAINT") > strings.Index(got, "ADD CONSTRAINT") {
		t.Error("constraint must be dropped before it is re-added")
	}
}

func TestDropTableOrdersDependentsFirst(t *testing.T) {
	old := snap(t, s.MySQL, users(), posts())
	cur := snap(t, s.MySQL)
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	if strings.Index(got, "DROP TABLE `posts`") > strings.Index(got, "DROP TABLE `users`") {
		t.Errorf("posts references users, so it must be dropped first:\n%s", got)
	}
	if len(p.Warnings()) != 2 {
		t.Errorf("want a warning per dropped table, got %v", p.Warnings())
	}
}

func TestSQLiteInPlaceAlters(t *testing.T) {
	old := snap(t, s.SQLite, s.Table("t", s.Int("id").PrimaryKey(), s.Text("a"), s.Text("old_name").Nullable()))
	cur := snap(t, s.SQLite, s.Table("t", s.Int("id").PrimaryKey(), s.Text("a"), s.Text("new_name").Nullable().RenamedFrom("old_name"), s.Int("n").Default(0), s.Index("a")))
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	mustContain(t, got, `RENAME COLUMN "old_name" TO "new_name"`, `ADD COLUMN "n" INTEGER NOT NULL DEFAULT 0`, `CREATE INDEX "idx_t_a"`)
	mustNotContain(t, got, "__lathe_new_")
}

func TestSQLiteRebuild(t *testing.T) {
	old := snap(t, s.SQLite,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("t", s.Int("id").PrimaryKey(), s.Int("u_id").Nullable(), s.Text("n").Nullable(), s.Index("u_id")),
	)
	cur := snap(t, s.SQLite,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("t", s.Int("id").PrimaryKey(), s.Int("u_id").Nullable().References("u", "id"), s.Text("n").Default("z"), s.Index("u_id"), s.Text("extra").Nullable()),
	)
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	mustContain(t, got,
		`CREATE TABLE "__lathe_new_t"`,
		`CONSTRAINT "fk_t_u_id" FOREIGN KEY ("u_id") REFERENCES "u" ("id")`,
		// rows are copied, and NULLs are replaced by the new default
		`INSERT INTO "__lathe_new_t" ("id", "u_id", "n") SELECT "id", "u_id", COALESCE("n", 'z') FROM "t"`,
		`DROP TABLE "t"`,
		`ALTER TABLE "__lathe_new_t" RENAME TO "t"`,
		`CREATE INDEX "idx_t_u_id" ON "t" ("u_id")`,
	)
	// the inverse rebuild restores the old shape
	dn := down(t, p, d)
	mustContain(t, dn, `CREATE TABLE "__lathe_new_t"`)
	mustNotContain(t, dn, "FOREIGN KEY", `"extra"`)
}

func TestSQLiteAddNotNullColumnRebuilds(t *testing.T) {
	old := snap(t, s.SQLite, s.Table("t", s.Int("id").PrimaryKey()))
	cur := snap(t, s.SQLite, s.Table("t", s.Int("id").PrimaryKey(), s.Text("x")))
	p, d := diff(t, old, cur)
	mustContain(t, up(t, p, d), `__lathe_new_t`)
}

func TestMySQLStringEscaping(t *testing.T) {
	cur := snap(t, s.MySQL, s.Table("t", s.Int("id").PrimaryKey(), s.VarChar("q", 10).Default(`it's a \ test`)))
	p, d := diff(t, nil, cur)
	mustContain(t, up(t, p, d), `DEFAULT 'it''s a \\ test'`)
}

func TestWideningIsNotAWarning(t *testing.T) {
	old := snap(t, s.Postgres, s.Table("t",
		s.Int("id").PrimaryKey(),
		s.VarChar("a", 10), s.Int("n"), s.Money("m"), s.Enum("e", "x"), s.Text("z"),
	))
	safe := snap(t, s.Postgres, s.Table("t",
		s.Int("id").PrimaryKey(),
		s.VarChar("a", 50), s.BigInt("n"), s.Decimal("m", 24, 4), s.Enum("e", "x", "y"), s.Text("z"),
	))
	if p, _ := diff(t, old, safe); len(p.Warnings()) != 0 {
		t.Errorf("widening must not warn: %v", p.Warnings())
	}
	risky := snap(t, s.Postgres, s.Table("t",
		s.Int("id").PrimaryKey(),
		s.VarChar("a", 5), s.SmallInt("n"), s.Decimal("m", 10, 2), s.Enum("e", "y"), s.VarChar("z", 20),
	))
	if p, _ := diff(t, old, risky); len(p.Warnings()) != 5 {
		t.Errorf("want 5 warnings for narrowing changes, got %v", p.Warnings())
	}
}

// Dropping a table that references a table which is renamed in the same
// migration: the down migration must undo the rename before it recreates the
// dropped table, whose foreign key names the old table name.
func TestDownRestoresRenamedTargetBeforeRecreatingDroppedTable(t *testing.T) {
	for _, dialect := range []s.Dialect{s.Postgres, s.MySQL, s.SQLite} {
		t.Run(string(dialect), func(t *testing.T) {
			old := snap(t, dialect,
				s.Table("tags", s.Int("id").PrimaryKey()),
				s.Table("post_tags", s.Int("tag_id").PrimaryKey().References("tags", "id")),
			)
			cur := snap(t, dialect, s.Table("labels", s.Int("id").PrimaryKey()).RenamedFrom("tags"))
			p, d := diff(t, old, cur)
			upSQL := up(t, p, d)
			if strings.Index(upSQL, "DROP TABLE") > strings.Index(upSQL, "RENAME") {
				t.Errorf("the table must be dropped before the rename:\n%s", upSQL)
			}
			dn := down(t, p, d)
			back := strings.Index(dn, "RENAME")
			recreate := strings.Index(dn, "CREATE TABLE "+d.Quote("post_tags"))
			if back < 0 || recreate < 0 || back > recreate {
				t.Errorf("rename must be undone before post_tags is recreated:\n%s", dn)
			}
		})
	}
}

func TestForeignKeyDropUsesPreRenameTableName(t *testing.T) {
	old := snap(t, s.Postgres,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("a", s.Int("id").PrimaryKey(), s.Int("u_id").References("u", "id")),
	)
	cur := snap(t, s.Postgres,
		s.Table("u", s.Int("id").PrimaryKey()),
		s.Table("b", s.Int("id").PrimaryKey(), s.Int("u_id")).RenamedFrom("a"),
	)
	p, d := diff(t, old, cur)
	got := up(t, p, d)
	if strings.Index(got, `ALTER TABLE "a" DROP CONSTRAINT`) < 0 {
		t.Errorf("the FK must be dropped from the table under its old name:\n%s", got)
	}
	if strings.Index(got, `DROP CONSTRAINT`) > strings.Index(got, `RENAME TO "b"`) {
		t.Errorf("FK drop must precede the rename:\n%s", got)
	}
}
