package ddl

import (
	"fmt"
	"strings"

	"github.com/tobibamidele/lathe/schema"
)

type postgres struct{}

func (postgres) Name() schema.Dialect          { return schema.Postgres }
func (postgres) Quote(s string) string         { return quoteWith(`"`, s) }
func (postgres) CanAlterForeignKeys() bool     { return true }
func (p postgres) q(s string) string           { return p.Quote(s) }
func (p postgres) alter(t string) string       { return "ALTER TABLE " + p.q(t) + " " }
func (p postgres) DropTable(n string) []string { return []string{"DROP TABLE " + p.q(n)} }

func (p postgres) RenameTable(from, to string) []string {
	return []string{p.alter(from) + "RENAME TO " + p.q(to)}
}

func (p postgres) typeSQL(c *schema.ColumnDef) string {
	t := c.Type
	switch t.Kind {
	case schema.KindSmallInt:
		return "SMALLINT"
	case schema.KindInt:
		return "INTEGER"
	case schema.KindBigInt:
		return "BIGINT"
	case schema.KindReal:
		return "REAL"
	case schema.KindDouble:
		return "DOUBLE PRECISION"
	case schema.KindDecimal:
		return fmt.Sprintf("NUMERIC(%d, %d)", t.Precision, t.Scale)
	case schema.KindBool:
		return "BOOLEAN"
	case schema.KindVarChar:
		return fmt.Sprintf("VARCHAR(%d)", t.Length)
	case schema.KindText, schema.KindEnum:
		return "TEXT"
	case schema.KindUUID:
		return "UUID"
	case schema.KindTimestamp:
		return "TIMESTAMPTZ"
	case schema.KindDate:
		return "DATE"
	case schema.KindJSON:
		return "JSONB"
	case schema.KindBytes:
		return "BYTEA"
	}
	panic("ddl: unknown kind " + string(t.Kind))
}

func (p postgres) defaultSQL(c *schema.ColumnDef) string {
	d := c.Default
	switch d.Kind {
	case schema.DefaultNow:
		if c.Type.Kind == schema.KindDate {
			return "CURRENT_DATE"
		}
		return "now()"
	case schema.DefaultUUID:
		return "gen_random_uuid()"
	case schema.DefaultExpr:
		return "(" + d.Value + ")"
	}
	return literal(c, sqlString, "TRUE", "FALSE")
}

func (p postgres) checkExpr(c *schema.ColumnDef) string {
	return fmt.Sprintf("%s IN (%s)", p.q(c.Name), enumList(c.Type.Values, sqlString))
}

func (p postgres) columnDef(table string, c *schema.ColumnDef) string {
	var b strings.Builder
	b.WriteString(p.q(c.Name) + " " + p.typeSQL(c))
	if c.AutoIncrement {
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	}
	if !c.Nullable {
		b.WriteString(" NOT NULL")
	}
	if c.Default != nil {
		b.WriteString(" DEFAULT " + p.defaultSQL(c))
	}
	if c.Type.Kind == schema.KindEnum {
		fmt.Fprintf(&b, " CONSTRAINT %s CHECK (%s)", p.q(checkName(table, c.Name)), p.checkExpr(c))
	}
	return b.String()
}

func (p postgres) CreateTable(t *schema.TableDef, inline []*schema.ForeignKeyDef) []string {
	var parts []string
	for _, c := range t.Columns {
		parts = append(parts, p.columnDef(t.Name, c))
	}
	parts = append(parts, "PRIMARY KEY ("+quoteList(p, t.PrimaryKey)+")")
	for _, fk := range inline {
		parts = append(parts, foreignKeyClause(p, fk))
	}
	out := []string{createTableSQL(p, t.Name, parts)}
	for _, ix := range t.Indexes {
		out = append(out, createIndex(p, t.Name, ix))
	}
	return out
}

func (p postgres) AddForeignKey(table string, fk *schema.ForeignKeyDef) []string {
	return []string{p.alter(table) + "ADD " + foreignKeyClause(p, fk)}
}

func (p postgres) DropForeignKey(table string, fk *schema.ForeignKeyDef) []string {
	return []string{p.alter(table) + "DROP CONSTRAINT " + p.q(fk.Name)}
}

func (p postgres) AlterTable(c *TableChange) ([]string, error) {
	table := c.New.Name
	var out []string
	for _, ix := range c.DropIndexes {
		out = append(out, "DROP INDEX "+p.q(ix.Name))
	}
	for _, col := range c.DropColumns {
		out = append(out, p.alter(table)+"DROP COLUMN "+p.q(col.Name))
	}
	for _, r := range c.RenameColumns {
		out = append(out, p.alter(table)+"RENAME COLUMN "+p.q(r.From)+" TO "+p.q(r.To))
	}
	for _, a := range c.AlterColumns {
		out = append(out, p.alterColumn(table, a)...)
	}
	for _, col := range c.AddColumns {
		out = append(out, p.alter(table)+"ADD COLUMN "+p.columnDef(table, col))
	}
	for _, ix := range c.AddIndexes {
		out = append(out, createIndex(p, table, ix))
	}
	return out, nil
}

func (p postgres) alterColumn(table string, a ColumnAlter) []string {
	old, cur := a.Old, a.New
	col := p.alter(table) + "ALTER COLUMN " + p.q(cur.Name) + " "
	var out []string

	oldCheck := old.Type.Kind == schema.KindEnum
	newCheck := cur.Type.Kind == schema.KindEnum
	checkChanged := oldCheck != newCheck || (oldCheck && !sameStrings(old.Type.Values, cur.Type.Values))
	if oldCheck && checkChanged {
		out = append(out, p.alter(table)+"DROP CONSTRAINT "+p.q(checkName(table, cur.Name)))
	}

	typeChanged := p.typeSQL(old) != p.typeSQL(cur)
	defaultDropped := false
	if typeChanged && old.Default != nil {
		// a default cannot always be cast implicitly, so drop it and set it again
		out = append(out, col+"DROP DEFAULT")
		defaultDropped = true
	}
	if typeChanged {
		ty := p.typeSQL(cur)
		out = append(out, col+"TYPE "+ty+" USING "+p.q(cur.Name)+"::"+ty)
	}
	if old.Nullable != cur.Nullable {
		if cur.Nullable {
			out = append(out, col+"DROP NOT NULL")
		} else {
			out = append(out, col+"SET NOT NULL")
		}
	}
	switch {
	case cur.Default != nil && (defaultDropped || !defaultsEqual(old, cur)):
		out = append(out, col+"SET DEFAULT "+p.defaultSQL(cur))
	case cur.Default == nil && old.Default != nil && !defaultDropped:
		out = append(out, col+"DROP DEFAULT")
	}
	if old.AutoIncrement != cur.AutoIncrement {
		if cur.AutoIncrement {
			out = append(out, col+"ADD GENERATED BY DEFAULT AS IDENTITY")
		} else {
			out = append(out, col+"DROP IDENTITY")
		}
	}
	if newCheck && checkChanged {
		out = append(out, fmt.Sprintf("%sADD CONSTRAINT %s CHECK (%s)", p.alter(table), p.q(checkName(table, cur.Name)), p.checkExpr(cur)))
	}
	return out
}

func defaultsEqual(a, b *schema.ColumnDef) bool {
	switch {
	case a.Default == nil && b.Default == nil:
		return true
	case a.Default == nil || b.Default == nil:
		return false
	}
	return *a.Default == *b.Default
}
